### ISSUE TITLE
マップ系パッケージの選定

### ISSUE THREAD

**Issue by susatthi** [team-musashi/stamp-rally#11]
おそらく、GoogleMapのようなマップ系パッケージを使う可能性が高いので、いくつかあるマップ系パッケージを調査して最適なパッケージを選定をお願いします。

現時点で想定される使い方は以下の通りです（変わる可能性もあります）。

- 出発点と到着点を指定して最適なルートを表示する（経路機能）
- マップ上にピンを立てられる
  - ピンをタップすると位置情報に紐付いた画像（写真）をポップアップ表示する

**Comment by susatthi** [comment]
@nzmgfdprs 

調べたことをまとめる or 調べたことをまとめたリンクを貼り付けるなどして、CloseできたらCloseしちゃってくださいー

**Comment by nzmgfdprs** [comment]
## マップ系パッケージをいろいろと試してみる
### main packages
- google_maps_flutter
- flutter_map
### sub packages（用途によっては下記パッケージも使用する必要がある）
- flutter_google_places
  - 住所検索のために使用
- geolocator
  - 検索した住所から緯度・経度を取得するために使用
- flutter_polyline_points
  - 任意の２点間の現実的かつ最適なルートを取得するために使用
- latlong2
  - flutter_mapを使用する際に必要
  
### 調査
| | google_maps_flutter | flutter_map| 備考 |
| :-- | :-- | :-- | :-- |
| 導入の手軽さ | ○ | ○ | どれも変わらなそう。用途によって他パッケージのインストール必要 |
| 現在地を表示できるか | ○ | △（geocodingパッケージとの連携必要） | google_maps_flutterは単体で使用できるから良さそう |
| 向いている方向を取得できるか | ○ | △（geocodingパッケージとの連携必要）| google_maps_flutterは単体で使用できるから良さそう |
| アイコン変更可否 | ○ | ○ | |
| マップにピンを立てられるか | ○ | ○ | |
| 経路機能が使用できるか | △（flutter_polyline_pointsパッケージとの連携必要）| △（flutter_polyline_pointsパッケージとの連携必要） | Directions APIを使用するので導入時からGoogle Map APIを使用するgoogle_maps_flutterの方が相性が良さそう |
| 料金 | 1 か月 200 ドル分まで無料。地図の読み込みは 1 か月あたり 28,500 回まで無料。その無料枠を超えたら使用した分だけ料金がかかる(従量課金) ただし、上限設定が可能なので最悪の場合の高額請求を防ぐことができる。| オープンソースのマップAPIを使用する場合は無料。デフォルトはオープンソース | |

### 調査結果
- 機能面や学習コスト、利用者数の多さからGoogleMapAPIを用いるのが良さそう。また、API上限設定(1日の表示上限、100秒間の表示上限、100秒間かつ1ユーザーの表示上限 それぞれに対して)も可能なため高額に請求されてしまうという不測の事態を防ぐことができると考えた。
- 予算アラートの設定によって上限に近づいた時に通知がくるように設定もできる。
- よってgoogle_maps_flutterパッケージを使用することにする。

### 参考リンク
- [地図パッケージを比較してみた](https://zenn.dev/odaken/articles/615f12930c7f5d)
- [Google Maps Platform レポート](https://developers.google.com/maps/reporting/gmp-reporting?hl=ja)
- [Google Maps PlatformのAPI 使用の上限設定](https://ring-and-link.co.jp/dream2000/user/notice/web/2975)](https://ring-and-link.co.jp/dream2000/user/notice/web/2975)
