### ISSUE TITLE
発表前の細かい修正

### ISSUE THREAD

**Issue by susatthi** [team-musashi/stamp-rally#110]
## 関連する Issue

- なし

## 内容

- [x] BRARRY ？BRALLY？
- [x] README
- [x] ワーディング
- [x] 参加中スタンプラリーがないときの表示
- [x] 完了画面でスタンプラリーが無いときに表示するメッセージ
- [x] 公開スタンプラリーのマップ表示対応
- [x] Firebase Storage Rule の更新
- [x] v0.5.0に上げる
- [x] APIキーは環境変数に変更

## 目的

- 発表向けに完成度を上げる

**Comment by ego-nemo** [comment]
めちゃくちゃ今更ですけど思いっきり綴り間違ってますね。
ロゴ含めて修正しないと。（どの時点から間違ってたのか分からんが原因は多分俺）

**Comment by susatthi** [comment]
@ego-nemo 
直せそうならお願いします！必須じゃないです！

**Comment by susatthi** [comment]
@ego-nemo 

https://github.com/team-musashi/stamp-rally/issues/93#issuecomment-1362827205
でロゴもらいましたが、ログイン画面でつかう白抜きのロゴも欲しいです！

![Screenshot_1671745386](https://user-images.githubusercontent.com/13707135/209231238-480bdb84-f852-4114-977c-30e99826d8e1.png)

**Comment by keishimizu26629** [comment]
@susatthi 
対応しました！ご確認お願いします！
https://www.figma.com/file/2ZM1CGT4hcVK6DoQaKRWcD/BURALLY?node-id=0%3A1&t=bDb2P1AHBI4zAI0p-1
