### ISSUE TITLE
GoogleMaps 高額課金対応

### ISSUE THREAD

**Issue by yuto-wl** [team-musashi/stamp-rally#120]
## 問題詳細

- 何らかのバグで 12/20 〜 12/22 に DirectionsAPI に対して大量のリクエストが発生した。
- 上記が原因で高額の課金が発生してしまっている。

## 現在の対応状況

- Googleへお願いのメールを送り返信待ち。
- マップのルート機能を一時的にオミット済み。

### 今後必要と思われる対応

1. GoogleMapsPlatform から Directions API リクエストの割り当てを行い、無料枠を超えないようにする。
2. バグの原因究明を行う。
3. リリース後、無料枠を超えないか改めて試算する。

**Comment by yuto-wl** [comment]
> GoogleMapsPlatform から Directions API リクエストの割り当てを行い、無料枠を超えないようにする。

今日やっておきます。

> バグの原因究明を行う。

@nozomi-koborinai 
現在判明している部分の記載と、もし可能なら原因究明お願いします。

**Comment by yuto-wl** [comment]
> GoogleMapsPlatform から Directions API リクエストの割り当てを行い、無料枠を超えないようにする。

対応しました。
無制限であったリクエスト上限を
- 1日のリクエスト上限を 1000
- 1分のリクエスト上限を 200
- ユーザーごとの1分のリクエスト上限を 100
に引き下げました。

1. 1日1000リクエストまで
2. 1000リクエストあたり4ドル
3. 最大でも月間120ドル
4. 毎月200ドルの無料枠がある
5. 最大使用料金120ドル < 無料枠200ドル

基本問題ないはずですが、何かあればご連絡ください。

**Comment by yuto-wl** [comment]
prod はまだキー発行していなかったので、対応していません。
忘れないようにしないと・・・

**Comment by nozomi-koborinai** [comment]
>バグの原因究明を行う。  

**12/21の12時〜18時**にDirections APIに大量のリクエストがあったことがわかりました。
ちょうどその時間帯は、マップ周りのコード修正を行なっており、その修正の中で大量にDirections APIが呼ばれてしまうコードがあったのだろうと考えられます。
ただ、どのような書き方で大量にDirections APIがコールされたのかは不明です....すみません。
![CleanShot 2023-01-11 at 10 47 24@2x](https://user-images.githubusercontent.com/39579511/211887080-61978529-6239-41c7-ba3f-ba214f88d1cb.png)
![CleanShot 2023-01-11 at 10 48 59@2x](https://user-images.githubusercontent.com/39579511/211886994-8b370a70-792e-43dd-864f-da80e8c68af9.png)

**Comment by nozomi-koborinai** [comment]
@yuto-wl 
>GoogleMapsPlatform から Directions API リクエストの割り当てを行い、無料枠を超えないようにする。

対応していただきありがとうございます！助かります🙇‍♂️

**Comment by susatthi** [comment]
みなさま、ご迷惑をおかけして申し訳ございません。
経路APIの大量リクエストの原因が分かりました。

以下の修正によって現状は問題無いコードになっています。
https://github.com/team-musashi/stamp-rally/commit/5ed96c8b1c4acf680539da27802355b41b63af41

### 直接的原因

地図表示をするWidgetである `SpotMapView` のビルド内で経路APIを実行しており、そのビルドが無限ループで実行されていたため。

### 本質的原因

問題のあるコードでは、Riverpodのfamilyの引数に `List<GeoLocation>` を与えていました。引数を `StampRally` に変更することで修正されました。

Riverpodのfamilyを使うと、引数に応じた値を返します。同じ引数だった場合は再実行されずキャッシュが返ります。
同じかどうかの判定は `==` （実体は`Object.hashCode` の比較）が用いられます。

<img width="1451" alt="CleanShot 2023-01-13 at 11 47 48@2x" src="https://user-images.githubusercontent.com/13707135/212225749-79838484-bf2f-415f-a7ca-4e0c4ab6d9ff.png">


https://riverpod.dev/ja/docs/concepts/modifiers/family

Riverpodのfamilyに`List`を与えた場合を考えてみます。

`List`は中身がまったく同じであっても `List` インスタンス自体が異なると、`==` の結果は `false` になります。ちなみに、中身が同じかどうかの判定は `listEquals()` を使います。

```dart
final fruits1 = ['apple', 'banana'];
final fruits2 = ['apple', 'banana'];
print(fruits1 == fruits2); // => false
print(listEquals(fruits1, fruits2)); // => true
```

今回の問題が起きるとき、familyの引数に与えていた`List<GeoLocation>`の中身は同じだけどインスタンス自体が毎回異なっていました。従ってキャッシュが返ることはなく、毎回実行されていました。

なお、`List<GeoLocation>`のインスタンス自体が毎回異なるのは freezed パッケージの仕様です。

freezed によって生成されたインスタンスは、中身の値が同じなら同じ値を返すように `hashCode` を override しています。しかし、freezedによって生成されたインスタンス内部の`List`を取り出して比較した場合、その`List` は freezed の管轄外になるので、結果は `false` になります。

```dart
final fruits1 = Fruit(value: ['apple', 'banana']);
final fruits2 = Fruit(value: ['apple', 'banana']);
print(fruits1 == fruits2); // => true
print(fruits1.value == fruits2.value); // => false
```

以上を踏まえて、経路APIを無限に呼び出す手順は次の通りでした。

1. ユーザーがマップを表示する
2. `SpotMapView` がビルドされる
3. ビルド内で `ref.watch(currentPolylinePointsProvider(locations))` を呼ぶ
4. `currentPolylinePointsProvider` は `FutureProvider` なので、いったん `AsyncLoading()` を返す
5. 画面にマップが表示される
6. `currentPolylinePointsProvider(locations)` 内で経路APIを実行して経路情報が確定する
7. 経路情報が確定したので `SpotMapView` がリビルドされる
8. ビルド内で `ref.watch(currentPolylinePointsProvider(locations))` を呼ぶ
9. このとき引数に渡す `locations` は手順3で渡した `locations` と中身は同じだがインスタンスが異なるためキャッシュを返さず、`AsyncLoading()` を返す
　→手順5に戻る

### 現状のコードで問題ない理由

以下の修正によって`currentPolylinePointsProvider` に渡す引数を `List<GeoLocation>` から `StampRally` に変更しました。この修正によって、上記手順の6で、キャッシュが返るようになり、無限ループにならずに済むようになりました。

https://github.com/team-musashi/stamp-rally/commit/5ed96c8b1c4acf680539da27802355b41b63af41

### 教訓

Riverpod の family には `List` や `Map` を与えてはいけない

**Comment by yuto-wl** [comment]
@nozomi-koborinai @susatthi 

調査ありがとうございます！
個人的にも勉強になりました。

オミットしていた機能は別 issue で戻して、次回MTG前後でこちらも Close します。

**Comment by susatthi** [comment]
@nozomi-koborinai @yuto-wl 

現状はアプリから経路APIを呼び出していますが、そうではなく、あらかじめ経路APIを実行して得られた結果をFirestoreに保存しておいて、アプリはその値を取得・表示するだけのほうがよい気がしました。

手作業で経路APIを実行した結果をFirestoreに保存してもよいですし、
GAS経由でスポット情報をFirestoreに書き込んだタイミングで、CloudFunctions内で経路APIを実行してFirestoreに保存するのがよさそうです。

その上で、現在はユーザーの現在地からスポット1番目の位置まで経路APIを実行していたと思いますが（していないかも）、
ユーザーの現在地がマップ上に表示されれば、わざわざ経路の線を引く必要もないとも思いました。

これで、アプリから経路APIを呼び出す必要はなくなります。

正しいコードになったとしても、維持費が高くなる可能性が残っているので直した方が良いと思いました！
みなさんで相談して決めて下さい！

**Comment by yuto-wl** [comment]
@susatthi 
返信遅くなってしまいすみません！
ご提案ありがとうございます。

次回MTGで拡張性なども鑑み実装の相談します！

**Comment by nozomi-koborinai** [comment]
#126 の対応によって、Functions でのみ経路APIをコールするようになったので本Issueもクローズします。
たくさん勉強になったIssueで面白かったです！
