### ISSUE TITLE
オミットしていたルート機能の復元

### ISSUE THREAD

**Issue by yuto-wl** [team-musashi/stamp-rally#121]
## 関連する Issue

- #118 
- #120

## 内容
調査が完了 & リクエスト上限の設定が完了したため、オミットしていた機能を復元する。

**Comment by yuto-wl** [comment]
@nozomi-koborinai 
お手数おかけしますが、こちらお願いします。

**Comment by nozomi-koborinai** [comment]
@yuto-wl 
経路情報をFirestoreに保持して、アプリ側からは経路APIを呼ばなくする対応について、引き続きこのIssue（#121）で対応しても大丈夫ですか？
https://github.com/team-musashi/stamp-rally/issues/120#issuecomment-1382406664

**Comment by yuto-wl** [comment]
@nozomi-koborinai 

> 経路情報をFirestoreに保持して、アプリ側からは経路APIを呼ばなくする対応について、引き続きこのIssueで対応しても大丈夫ですか？

すみません、こちらいくつか気になる点があるので次回MTGで相談させてください。
一旦このissueはクローズします。
