### ISSUE TITLE
スタンプラリー終了処理の表記の修正

### ISSUE THREAD

**Issue by yuto-wl** [team-musashi/stamp-rally#127]
## 内容

現在スタンプラリーを終了しようとした際、「完了」「中断」から選択して終了する仕様になっている。
しかし実態は、
- 「完了」はスタンプラリー完了画面から結果を確認できる
- 「中断」は結果を確認できない

という仕様になっていて「完了」「中断」といった命名にそぐわない。

よって、
1. ダイアログに「中断した際は結果が保存されない」という一文を追記する。

また、実装検討に中断からの再開を追加する。

![スクリーンショット 2023-01-18 23 21 40](https://user-images.githubusercontent.com/61089654/213195899-912a8168-a212-408a-a189-ac75aadc7ffa.png)

## 目的
挙動がわかりやすいようにダイアログを修正する。

**Comment by yuto-wl** [comment]
@ego-nemo 
一人で修正できそうならお願いします！

助けが必要そうならお手伝いしますのでお声がけください。

**Comment by ego-nemo** [comment]
@yuto-wl おけです
一旦一人でやってみます
詰んだらお願いします

**Comment by yuto-wl** [comment]
@ego-nemo 
確認しました。
マージお願いします！
