### ISSUE TITLE
最初の画面のUIデザインの作成

### ISSUE THREAD

**Issue by susatthi** [team-musashi/stamp-rally#21]
## 関連する Issue

- #13 

## 内容

以下の２つの画面のＵＩデザインの作成をお願いします。アプリの世界観がわかるようにしてほしいです。Figma推奨ですが、Figma以外でもOKです。

１．ログイン画面（インストール直後、最初に表示される画面（左））
２．ホーム画面（プライバシーポリシーとサービス利用規約に同意し匿名ユーザーになったあと、アプリ起動すると最初に表示される画面（右））

<img width="580" alt="CleanShot 2022-11-11 at 11 23 01@2x" src="https://user-images.githubusercontent.com/13707135/201248647-869e6eaf-17bc-4c90-bdc3-2abb66d38ad6.png">

上記画像の資料は以下にあります。
https://docs.google.com/spreadsheets/d/1yE6WShcF46s0hiAF9sy4t7pQsU3F4NUSVu8ykkhxwvc/edit#gid=0

### ログイン画面の要件

- プライバシーポリシーとサービス利用規約に同意して始めることが出来る
- ボタンは「はじめる」とか「同意してはじめる」とかかなぁ。

### ホーム画面の要件

- 参加できるスタンプラリー一覧が表示されている
  - スタンプラリーをタップしたらスタンプラリー詳細にいける（詳細画面は本Issueのスコープ対象外）
- AppBarやボトムナビゲーションバーをつけるかどうかも検討してほしいです。

## 目的

- 要件の明確化

**Comment by susatthi** [comment]
マテリアルデザイン3でやりましょう！

**Comment by ego-nemo** [comment]
### ログイン画面とホーム画面のデザイン（仮）
**意識したこと**

- Instagramなどのオサレ系SNSを参考
- SNSとの連携を鑑み、SNSログインを設置（現時点で必要なければ一旦オミット）
- 女性ユーザーを想定した配色、デザイン
- シャープというよりも丸みを帯びた見た目
- 写真をメインに押し出すというコンセプトを基に写真が映えそうな配置を意識
- 各ボタン、インタラクト部分をタップした時のアニメーションを付与して操作する際の気持ちよさ（？）を演出してみる

**検討事項**

- 色合いの濃淡、※派手すぎる ※チカチカするなど
- あるいはそもそものデザインが適正なのか
- 開催スタンプラリー一覧画面のデザインが適正か。表示イメージをスクロールさせるか否か、または代案
- インタラクト時のアニメーションの是非
- ホーム画面に表示させる情報の整理（必要なものとそうでないもの）
- ボトムナビゲーションに配置する項目の精査
- アップバー、もしくはトップナビゲーションが要るかどうか
- 他、追加する要件など

**今後やろうとしていること**

- マップ画面のUI作成
- カメラ画面のUI作成
- お知らせ画面のUI作成
- その他設定画面、アカウント画面のUI作成

[https://www.figma.com/file/NxKEdm3XAWdXzvbnf2oJEr/%E3%82%B9%E3%82%BF%E3%83%A9%E3%83%AA%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E6%A1%88%E3%83%97%E3%83%AD%E3%83%88%E3%82%BF%E3%82%A4%E3%83%97?node-id=0%3A1&t=NcXfaJfkFp0osAK6-1](url)

**Comment by susatthi** [comment]
リンクひらけないです

**Comment by susatthi** [comment]
リンクをテキストコピーしたらひらけました！

メールアドレスやソーシャルログイン機能は実装しないです。

**Comment by susatthi** [comment]
@ego-nemo 

12/1の打ち合わせでお伝えしたとおり、ホーム画面のデザインは以下の仕様でお願い致します！

<img width="516" alt="CleanShot 2022-12-02 at 05 03 11@2x" src="https://user-images.githubusercontent.com/13707135/205148683-40b599d7-ea05-4087-bd4b-647b12523424.png">

https://docs.google.com/presentation/d/1VH0R9AgLfwLYk2Kh-vY55sGbDwbDgLnEttlScndW0Qk/edit#slide=id.g1a09bb661bb_0_16

本Issueは、ホーム画面のデザインが作成できたらCloseしちゃいましょう〜

**Comment by susatthi** [comment]
@ego-nemo さんから slack で連絡きた

```
すみません大変遅くなりました！
前回のMTGで出たボトムナビのオミットと上部メニュータブ文言変更、設定ボタン追加
だけとりあえず変更しましたが、他に手を加える箇所はありますでしょうか？
前回MTGの保存動画を今一度確認して再度最終修正したいと思いますが、無ければこれでお願いします。
ロゴに関してはもう少し時間ください。
[https://www.figma.com/file/NxKEdm3XAWdXzvbnf2oJEr/%E3%82%B9%E3%82%BF%E3%83%A9%E3%83[…]%E3%82%BF%E3%82%A4%E3%83%97?node-id=0%3A1&t=WMERicFILitmCdso-1](https://www.figma.com/file/NxKEdm3XAWdXzvbnf2oJEr/%E3%82%B9%E3%82%BF%E3%83%A9%E3%83%AA%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E6%A1%88%E3%83%97%E3%83%AD%E3%83%88%E3%82%BF%E3%82%A4%E3%83%97?node-id=0%3A1&t=WMERicFILitmCdso-1)
```

**Comment by susatthi** [comment]
@ego-nemo 
cc: @keishimizu26629 

流れてよい連絡等はslackでOKですが、情報を残すべきやりとりはGitHubでお願いします！後から見返したいときに追えた方がよいので！

その上で質問です！

- おすすめ①でスタンプラリーをタップするとタップしたスタンプラリーが上部に移動するのではなく、ダイアログとして画面上部にモーダル表示する、でもよいでしょうか？下の方のスタンプラリーをタップしたときとか考慮し出すと①から②のアニメーションが結構大変だと思うので。。

- おすすめ②のシェアボタンと３点ボタンの意味を補足しておいてほしいです！

- スポット一覧はどこから遷移する想定ですか？下の図の赤枠がスポット一覧で、そこへ遷移するためのボタンが必要だと思います。あるいは③の概要テキストの下にスポット写真を並べるイメージですかね？

![CleanShot 2022-12-05 at 06 17 47@2x](https://user-images.githubusercontent.com/13707135/205516201-22680178-5634-4517-97c1-8a19bdb92286.png)

-

**Comment by susatthi** [comment]
@ego-nemo 
頼みます！修正版お待ちしています！

@kuwabara-hirokazu 
「考え中〜」のやつはegoさんへのインプット資料で、kuwaさん向けにはegoさんの資料を正としてほしいです！
んで、M3のセグメンテッドボタンはFlutter SDKに無く、また、記載頂いた https://pub.dev/packages/material_segmented_control は、私も試してみたんですが（２時間格闘した）、colorが固定だったり相当イマイチです。

ですので、セグメンテッドボタンではなくタブでいきましょう！
タブだと横スワイプにも対応できます。多少のデザイン差異はOKです！

![CleanShot 2022-12-06 at 05 31 37@2x](https://user-images.githubusercontent.com/13707135/205737336-14f06976-a807-46f7-9d97-04873d3905d5.png)

念のため、Figmaはここちらです！

https://www.figma.com/file/NxKEdm3XAWdXzvbnf2oJEr/スタラリデザイン案プロトタイプ?node-id=0%3A1&t=HSOfR9o3JGQWVVwU-1

**Comment by kuwabara-hirokazu** [comment]
>記載頂いた https://pub.dev/packages/material_segmented_control は、私も試してみたんですが（２時間格闘した）、colorが固定だったり相当イマイチです。

なるほど。確認までしていただきありがとうございます🙏

>ですので、セグメンテッドボタンではなくタブでいきましょう！
タブだと横スワイプにも対応できます。多少のデザイン差異はOKです！

タブを使うことで承知しました👌
ありがとうございます！

**Comment by ego-nemo** [comment]
@susatthi @kuwabara-hirokazu

ホーム画面からのラリー一覧表示から写真タップ時のアニメーションの件ですが、実装がややこしそうならダイアログ表示じゃなく、全部一旦無しにして、直接概要とスポット表示画面に飛ぶ仕様の方がいい気がしてきたので、そのようにしてもいいでしょうか？

公開中②、公開中③を無しにして、公開中①から公開中④に遷移させるイメージです。

公開中④の参加ボタンを押すと参加中画面の不参加時表示からアクティブに変化、元の画面のボタンは押下中になり（公開中画面からもう一度アクセスできるが、参加ボタンは色が変わって押せなくなる）以後参加中画面を再ログイン時の表示の初期値にします。

<img width="1092" alt="スクリーンショット 2022-12-06 15 04 40" src="https://user-images.githubusercontent.com/106313781/205833682-682882d5-f76b-4c2e-8255-d0894fac655d.png">

**Comment by susatthi** [comment]
@ego-nemo 

>直接概要とスポット表示画面に飛ぶ仕様の方がいい気がしてきたので、そのようにしてもいいでしょうか？

もちろん良いと思います！

**Comment by ego-nemo** [comment]
@susatthi 
ありがとうございます！他何かご意見あればお願いします。（忘れてるかもしれないので）なければ一旦武蔵さんにOK貰ってkuwaさんに依頼したいと思います。

次は完了済画面の修正とスポット詳細画面とりかかります。マップ画面とカメラ画面は一旦おいといていいですかね。

**Comment by susatthi** [comment]
@ego-nemo 

できあがったデザインを再確認とさせてください！

>次は完了済画面の修正とスポット詳細画面にとりかかります。マップ画面とカメラ画面は一旦おいといていいですかね。

上記でおっけーですー
ちなみに、カメラ画面はデザイン不要です！

**Comment by susatthi** [comment]
@ego-nemo 

ホーム画面のデザイン修正中ですかね。。。？

**Comment by susatthi** [comment]
@ego-nemo 

いいじゃないですか！これでいきましょう！よいと思います！

<img width="725" alt="CleanShot 2022-12-08 at 17 01 13@2x" src="https://user-images.githubusercontent.com/13707135/206391737-e0f89812-6633-4201-a975-f5dd8674a29b.png">

**Comment by susatthi** [comment]
ホーム画面のデザインはできたのでクローズ
残りは別Issueで対応
