### ISSUE TITLE
プライバシーポリシーと利用規約の仮ページを作成する

### ISSUE THREAD

**Issue by susatthi** [team-musashi/stamp-rally#23]
## 関連する Issue

- #22 

## 内容

- インストール直後に表示する画面でユーザーにプライバシーポリシーと利用規約に同意してもらいます。
- ユーザーがプライバシーポリシーと利用規約の文面を確認できるようにする必要があります。
- よってプライバシーポリシーと利用規約はWebで公開して誰でも見られるようにしてください。
- 文言は仮でよいので、その２つのページを用意してください。
- https://kiyac.app/ を試してみるとよいかも。

## 目的

- アプリ公開に必要

**Comment by keishimizu26629** [comment]
KIYACは有料プランが必要のため、新たにリポジトリを作成してGitHub Pagesで公開。

利用規約URL
https://team-musashi.github.io/stamp-rally-doc/terms-of-service.html
プライバシーポリシーURL
https://team-musashi.github.io/stamp-rally-doc/privacy-policy.html
