### ISSUE TITLE
スタンプラリーに参加できるようにする

### ISSUE THREAD

**Issue by susatthi** [team-musashi/stamp-rally#51]
## 関連する Issue

- #22
- #50 

## 内容

- スタンプラリー詳細画面に「参加する」ボタンを追加する
- 「参加する」ボタン押下でスタンプラリーに参加できるようにする
- ホーム画面のスタンプラリー一覧に、参加中のスタンプラリーを表示する
- デザインは未決定なので適当でOK

## 設計方針

こんな感じにしたい

<img width="1332" alt="CleanShot 2022-11-23 at 07 37 13@2x" src="https://user-images.githubusercontent.com/13707135/203435508-32c7d568-43d3-46a4-a921-fcf0190ee41c.png">

https://docs.google.com/presentation/d/1HoHE759nOUFlWs1OBNuClz9OU0wNyOJEitnxMo1RwaY/edit#slide=id.p

上記設計方針でやること

- Flutterアプリ
  - user/eventコレクションに「スタンプラリーに参加する」というイベントを追加する
  - user/entryStampRallyをstreamで監視しておく
- Firebase Firestore
  - user/event コレクションのセキュリティルールの実装
- Firebase Functions
  - onCreateUserEventの実装
    - user/event にドキュメントが追加されたら発火する
    - パラメータのstampRallyIdからpublicStampRallyを取得してきてuser/entryStampRallyおよびspotを作成する

**Comment by nzmgfdprs** [comment]
着手

**Comment by nzmgfdprs** [comment]
@susatthi 
eventコレクションのフィールド定義 及び functions発火後のデータ操作について整理してみたので確認お願いします！
下記リンクのコメント欄に記載しました。
https://docs.google.com/presentation/d/1HoHE759nOUFlWs1OBNuClz9OU0wNyOJEitnxMo1RwaY/edit#slide=id.p

**Comment by susatthi** [comment]
@nzmgfdprs 

コメント追記しました！

<img width="868" alt="CleanShot 2022-11-26 at 10 48 37@2x" src="https://user-images.githubusercontent.com/13707135/204067809-feb0113e-80fc-469d-a5e8-dbbac5e74f4b.png">

**Comment by susatthi** [comment]
@nzmgfdprs 

インフラストラクチャ層のEventドキュメントのDTO（EventDocument）の作り方について、以下のアイデアを思いついたので試してみて下さい！

以下はコンパイルしてません。イメージです。試していないのでうまくいかない可能性があります。実際はfreezedを使います。

```dart
abstract class EventDocument {
  final String eventType;
  final Map<String, dynamic> data;
  final DateTime createdAt;

  factory EventDocument.entryStampRally({
    required String stampRallyId,
  }) {
    return EntryStampRallyEventDocument(
      data:{
         'stampRallyId': stampRallyId, // enumにしたい
      },
      createdAt: DateTime.now(),
    );
  }
}

class EntryStampRallyEventDocument extends EventDocument {
  EntryStampRallyEventDocument({
    super.data,
    super.createdAt,  
  }): super(eventType: EventType.entryStampRally);
}

```

**Comment by susatthi** [comment]
@nzmgfdprs 

↑のアイデアは、riverpodのAsyncValueの定義から着想しました。AsyncValueの実装もチェックしてみてください！

https://github.com/rrousselGit/riverpod/blob/858872cdddb2f8b619841378c1df4b4242dc9c3e/packages/riverpod/lib/src/common.dart#L78

**Comment by susatthi** [comment]
@nzmgfdprs 
と思ったけど、Flutter側からはイベントを追加するだけだから、abstractやめてfactoryだけで良いことに気づきました。。。

**Comment by nozomi-koborinai** [comment]
進捗率：40%
次やること：eventドキュメント追加をトリガーとしてuser/entryStampRally および spotドキュメントにデータを書き込む処理の追加

**Comment by nozomi-koborinai** [comment]
進捗率：65%
やったこと：Firebaseリポジトリ側にeventおよびstampRallyに関する定義を追加。さらにそれらのコレクションをDIコンテナに登録
次やること：functions.onCreateUserEventの実装

**Comment by susatthi** [comment]
@nozomi-koborinai 

onCreateUserEvent => onCreateEvent にしてほしいです！ごめんなさい、資料上はonCreateUserEventでしたね。。

on＜メソッド＞＜コレクション名＞
というのが好みなので。。
前はuserコレクション下のサブコレクションだったから
onCreateUserEvent
にしてたけど、トップレベルに変更したのでUser消したいです。

**Comment by susatthi** [comment]
@nozomi-koborinai 

本当にごめんなさい。全体的に `Event`を`Command`に名称変更して欲しいです。
このあたりの実装は CQRS の考えに影響を受けています。CQRS ではイベントとコマンドは明確に役割が異なります。
ざっくり言うと、コマンドは命令で拒否される可能性があるもの、イベントは操作を記録するもので拒否される可能性がないもの、という違いがあります。

そういう意味では、「スタンプラリーに参加する」というのは**イベントではなくコマンドのほうが適切**でした。

コマンドとイベントの違いは
https://sipadan2003.blogspot.com/2013/12/cqrs.html
の「Greg Young流CQRSの和訳版」にあるPDFに書かれていました。
現在PDFがダウンロードできないようなので、以前ダウンロードしていたPDFをアップロードしておきます。

[cqrs_documents_jp.pdf](https://github.com/team-musashi/stamp-rally/files/10120562/cqrs_documents_jp.pdf)

P11あたりの以下の記述が参考になります。

<img width="770" alt="CleanShot 2022-11-30 at 16 26 05@2x" src="https://user-images.githubusercontent.com/13707135/204733475-a8044d68-bfa4-4d2b-bead-fbbc57f6be1a.png">

**Comment by nozomi-koborinai** [comment]
進捗率：75%
### やったこと
  - event -> commandへ名称変更
  - 一旦functionsにonCreateCommandを実装してみる（まだシミュレータでは試していない）
 
### 次やること
  - シミュレータで動作を確認
  - デプロイ

**Comment by nozomi-koborinai** [comment]
@susatthi 
とりあえず一通り、functionsに`onCreateCommand`関数を実装してみました！
ここで一旦レビューをお願いします<(_ _)>

https://github.com/team-musashi/stamp-rally-firebase/pull/13
