### ISSUE TITLE
ログイン画面のデザイン実装

### ISSUE THREAD

**Issue by susatthi** [team-musashi/stamp-rally#58]
## 関連する Issue

- #21 

## 内容

- ログイン画面のデザイン実装
- 枠組みは実装済みなので、#21 でデザインができあがったら着手する

**Comment by susatthi** [comment]
@ego-nemo 

ログイン画面のデザインが出来上がったら、このIssueを使ってkuwaさんに連絡よろです！

**Comment by keishimizu26629** [comment]
<img width="179" alt="image" src="https://user-images.githubusercontent.com/70187407/204117859-b448a3e4-ca82-4a6e-8bd2-b2adcd8c6e27.png">
@kuwabara-hirokazu 
ログイン画面の実装お願いします！色とロゴはあとで差し替える可能性もあります！

@susatthi 
画面について何かご指摘ありますか？利用規約・プライバシーポリシー同意の☑とかデザイン通りで特に大丈夫でしょうか？

**Comment by susatthi** [comment]
チェックボックスは無しでよいとおもいます！それ以外はおけです！

**Comment by kuwabara-hirokazu** [comment]
@keishimizu26629 @ego-nemo @susatthi 
流れとしては下記を想定していますか？

![スクリーン ショット 2022-11-27 に 14 00 15 午後](https://user-images.githubusercontent.com/62511320/204119985-36e224b4-f49b-4ee9-908c-147295609282.png)

@susatthi 
このissueチケットでやることの確認したいです🙋‍♂️
下記の認識で大丈夫ですか？

#### Scope
* 既存のログイン画面を新デザインに置き換える
#### Scope外
* スプラッシュ画面(アニメーション対応）
* 仕様に応じた画面ハンドリング 
  * 現状：初回のみ同意画面を表示、2回目以降はホームを表示
  * 上記仕様にする場合：初回のみスプラッシュ画面から同意画面を表示、2回目以降はスプラッシュ画面からホームに遷移させる

**Comment by susatthi** [comment]
@kuwabara-hirokazu 
スプラッシュ画面は対象外です！

**Comment by kuwabara-hirokazu** [comment]
@susatthi 
ロゴ画像やアイコン画像はsvgでよいですかね？
