### ISSUE TITLE
スポット詳細画面のワイヤーフレーム実装

### ISSUE THREAD

**Issue by susatthi** [team-musashi/stamp-rally#66]
## 関連する Issue

- #21

## 内容

- 公開スタンプラリー→公開スタンプラリー→スポット詳細という画面遷移にうち、最後のスポット詳細画面のワイヤーフレーム実装をお願いします。
- デザイン対応は別途やるので仕組み作りだけでOKです。

## 目的

- 要件を満たすため

**Comment by susatthi** [comment]
@yuto-wl 
developにもろもろマージされたので着手できます！

**Comment by yuto-wl** [comment]
ありがとうございます！
私の勘違いで #75 と一部内容を混同していてカメラ機能だけこちらで実装してしまいましたが、
無理に直すほどではないと思いますので、そのままにします。

こちら、プルリク時に改めて記載します。

**Comment by yuto-wl** [comment]
@susatthi 
公開中 Spot の情報([entity](https://github.com/team-musashi/stamp-rally/blob/develop/lib/domain/repository/stamp_rally/entity/spot.dart) 、[firebase側](https://github.com/team-musashi/stamp-rally-firebase/blob/develop/functions/src/firestore-collection/public-stamp-rally/entity/publicSpot.ts))
ですが、[スタンプラリーマスター_v1](https://docs.google.com/spreadsheets/d/1qDobYq0K2iJQzpKhFXX6yir1TT_rvhvuGXwBtXgG3Bs/edit#gid=1439600836) と齟齬が生じているように見えます( 実装側に[名称]、[詳細説明]がない )。
この issue で修正しても良いでしょうか？

**Comment by susatthi** [comment]
@yuto-wl 

お、、気づきましたね！さすがです！
Flutter側のEntityに名称と詳細説明を追加しておいてください！使わないかもですがー
