### ISSUE TITLE
デザイン対応（完了版）

### ISSUE THREAD

**Issue by susatthi** [team-musashi/stamp-rally#70]
## 関連する Issue

- #21

## 内容

- 2022/12/8 打ち合わせから
  - スタンプラリー一覧 => スタンプラリー詳細に遷移するとき、画面上部のタブ領域を無くす
  - マップ画面の細かいところはデザイン不要（実装者にお任せ）
  - 次の画面のデザインをお願いします
    - 公開中のスポット詳細画面
    - 参加中画面
      - 取得したスタンプ数を表示
      - まだ写真を撮ってない場合の表示もデザインする
    - 参加中のスポット詳細画面
    - 完了のスポット詳細画面は不要

## 目的

- 必須だから

**Comment by ego-nemo** [comment]
やったこと

- 参加中画面に達成スタンプのカウンターを設置
- 参加中画面に終了ボタンを配置（参加ボタンを押すと色が変わって終了ボタンに変わる）
- 参加中画面のスポット一覧をグレーアウトさせてNO IMAGE表記（仮）＋とかでも良い気がする
- スポット詳細画面作成
- 詳細画面にgoogleマップを開くボタン（確認ダイアログを出す）を仮で設置
- スタンプラリー一覧から詳細画面に遷移すると上部タブが隠されるパターンを追加
- 何も参加してない場合の参加中画面

やらないこと

- 完了画面の作成

**Comment by susatthi** [comment]
@ego-nemo 

Figmaにコメントしました！ご確認お願い致します！

**Comment by ego-nemo** [comment]
やったこと

- 公開中、参加中画面に所用時間の項目を追加
- ホーム画面以外の設定ボタンを削除
- 完了済写真一覧に番号付与
- 新ロゴ、アイコン1案作成

やらないこと

- 完了画面の作成

所感あればお願いします

**Comment by susatthi** [comment]
@ego-nemo 

1点、番号付与のところFigmaで質問しました！

**Comment by susatthi** [comment]
@ego-nemo 

Figmaの質問ご確認お願いします！

@keishimizu26629 

Figmaの画面デザインについて、OKなのか、修正が必要なところがないか、コメント頂きたいです！

**Comment by susatthi** [comment]
@ego-nemo 

>Figmaの質問ご確認お願いします！

回答頂いていて、デザイン修正済みを確認しました！（通知が来てなかったので見逃していましたすみません）

@keishimizu26629 

コメントお願いします！

**Comment by keishimizu26629** [comment]
@ego-nemo @susatthi 
全て確認しました！デザインOKです！

**Comment by susatthi** [comment]
対応完了、クローズ！
