### ISSUE TITLE
参加中画面の地図表示

### ISSUE THREAD

**Issue by susatthi** [team-musashi/stamp-rally#74]
## 関連する Issue

- #73

## 内容

- ホーム画面の「参加中」タブ選択したときの画面の地図表示の実装をお願いします。
- 細かいデザイン指定は無いので、操作性含めてお任せします。
- 要件
  - スポットの順番通りにルートを表示する
  - Google Map 風が望ましい

## 目的

- 要件を満たすため

**Comment by nozomi-koborinai** [comment]
@susatthi 
GoogleMapAPIキーを以下のAndroid および iOSファイルに設定するのですが、APIキーはどこで管理してどうやって以下のファイルに設定すればいいのでしょうか？
- android/app/src/main/AndroidManifest.xml
- ios/Runner/AppDelegate.swift

**Comment by nozomi-koborinai** [comment]
@susatthi
GoogleMapAPIキーを以下のAndroidファイル および iOSファイルに設定するのですが、APIキーはどこで管理すればよいでしょうか？
ちなみにGoogleMapAPIキーは取得済みです。

android/app/src/main/AndroidManifest.xml
ios/Runner/AppDelegate.swift

**Comment by KosukeSaigusa** [comment]
通りかかったので、もし参考になれば！

https://github.com/KosukeSaigusa/spajam-2022-final/blob/main/ios/Runner/AppDelegate.swift#L11

https://github.com/KosukeSaigusa/spajam-2022-final/blob/42874a5e8d0d758f96d7342842d539ee43210486/ios/.gitignore#L29

https://github.com/KosukeSaigusa/spajam-2022-final/blob/42874a5e8d0d758f96d7342842d539ee43210486/android/app/build.gradle#L67

※ iOS の方は、.gitignore した適当なファイル名（この例だと `ios/Runner/Environment.swift`）に API キーを入れることにしていますが、ただファイルを作るだけではだめで、XCode 上でドラッグアンドドロップして認識させる必要があります。

**Comment by susatthi** [comment]
Kosukeさん神！

**Comment by nozomi-koborinai** [comment]
@KosukeSaigusa @susatthi 
ありがとうございます！やってみます！

**Comment by susatthi** [comment]
緯度経度は以下からアップロードして動作確認につかってください

https://docs.google.com/spreadsheets/d/1qDobYq0K2iJQzpKhFXX6yir1TT_rvhvuGXwBtXgG3Bs/edit#gid=0

**Comment by susatthi** [comment]
12/20PR予定だった
