### ISSUE TITLE
参加中のスポット詳細画面のワイヤーフレーム実装

### ISSUE THREAD

**Issue by susatthi** [team-musashi/stamp-rally#75]
## 関連する Issue

- #73 が終わらないと着手できない

## 内容

- ホーム画面の「参加中」タブ選択したときの画面からスポットを選択したあとの画面のワイヤーフレーム実装をお願いします。
- デザイン対応は別途やるので仕組み作りだけでOKです。
- 要件
  - 公開中のほうと同様にスポットの詳細情報を表示する、ただし写真は撮影した写真を使う
  - カメラボタンを配置
    - 押下でカメラ機能を呼び出し、撮影して元の画面に戻り、撮影した画像を表示する
    - 保存をするとFirebase Storage に保存する
  - 写真を撮影したことがスポットを回ったことの判定条件にする
    - 参加中画面の回ったスポットの数が増えるようにする

## 目的

- 要件を満たすため

**Comment by susatthi** [comment]
打ち合わせメモ

- ユーザーがアップロードした画像はそのユーザーのみ閲覧可能とする
- Storageのフォルダ構成
  - /user/:userId/画像

**Comment by yuto-wl** [comment]
@susatthi 
すみません、上記コミット内で１箇所 [想定通りに動いてくれない箇所](https://github.com/team-musashi/stamp-rally/commit/44cc0516bcc8f67d65ed5ad748a4ba2aab76eef8#diff-39d543309b7ef9c526d09e245b151879137f6cbaa256bbc39aadbe569d51b84f) があるため、相談させてください。
アップロードの際 Firebase の uid を取得するため、
`final user = await ref.watch(userProvider.future);`
`final uid = user.id;`
としているのですが、uid を取得できません。

[FlutterでFirebase認証を開始する](https://firebase.google.com/docs/auth/flutter/start) の [userChanges] を参照したのですが、あまり理解できませんでした。
今の認識では「このメソッド経由で uid を参照するのは間違っていて、
`final auth = FirebaseAuth.instance;`
`final uid = auth.currentUser?.uid`;
のように別で取得する必要がある」と思っているのですが、正しいでしょうか？

**Comment by yuto-wl** [comment]
また、Storage のフォルダ構成ですが、拡張性に鑑みて以下のように変更いたしました。
問題があれば、ご連絡お願いいたします。
`'user/$uid/stamprally/$stamprallyId/spot/$spotId.jpg'`

**Comment by susatthi** [comment]
@yuto-wl 

>のように別で取得する必要がある」と思っているのですが、正しいでしょうか？

取得できるように直しました！
https://github.com/team-musashi/stamp-rally/commit/5df23b492a2b5d5070226d1b36f59d8cc0c1aa45

`userProvider.future` で取るのが正しいです！が、StreamProviderは、値が流れた後に `.future` しても、次の値が流れてこないとずっと待ち続けてしまいます。
なので、最初は値を返して、値が更新されたら再度流れてくる FutureProvider として定義し直しました！

>また、Storage のフォルダ構成ですが、拡張性に鑑みて以下のように変更いたしました。
問題があれば、ご連絡お願いいたします。

よいと思います！１点、jpgである保証は無いのかなと思ったので、拡張子は無しでよいと思います！
jpgである保証があればそのままでもOKです！
ちゃんとやるなら、画像のバイナリーデータのContent-Typeをみて拡張子を決める必要があります！

その他、現在の修正コードをみたコメントをしておきます！

- XXXService 内では `watch()` ではなく `read()` が基本です！`watch()` だと更新されるとそのメソッドが再実行されてしまいます。イベントハンドラーは原則 `read()` がよいです
- FirebaseStampRallyRepository内でuidが取れるので、FirebaseStampRallyRepositoryで、StampRallyとSpotとFileパスを受け取って、Firebase Storage のパスを構成するのがいいかもです！

```
    final uid = userDocRef?.id;
   ```

**Comment by yuto-wl** [comment]
> 取得できるように直しました！
https://github.com/team-musashi/stamp-rally/commit/5df23b492a2b5d5070226d1b36f59d8cc0c1aa45

> userProvider.future で取るのが正しいです！が、StreamProviderは、値が流れた後に .future しても、次の値が流れてこないとずっと待ち続けてしまいます。
> なので、最初は値を返して、値が更新されたら再度流れてくる FutureProvider として定義し直しました！

修正ありがとうございます！
なるほど、一回取得の場合は基本 FutureProvider なのですね。

> よいと思います！１点、jpgである保証は無いのかなと思ったので、拡張子は無しでよいと思います！
jpgである保証があればそのままでもOKです！
ちゃんとやるなら、画像のバイナリーデータのContent-Typeをみて拡張子を決める必要があります！

なるほど、ありがとうございます！
今回は一旦、拡張子無しでやってみます！

> XXXService 内では watch() ではなく read() が基本です！watch() だと更新されるとそのメソッドが再実行されてしまいます。イベントハンドラーは原則 read() がよいです

ご指摘ありがとうございます！
なんとなく意識しているつもりだったのですが、今回抜けてしまっていました！

> FirebaseStampRallyRepository内でuidが取れるので、FirebaseStampRallyRepositoryで、StampRallyとSpotとFileパスを受け取って、Firebase Storage のパスを構成するのがいいかもです！

確かにこちらの方がきれいな実装な気がしますね。
試してみます！ありがとうございます！

**Comment by susatthi** [comment]
- 写真をとる、バイナリデータが手元にある
- バイナリデータをStorageにアップロードして、URLを取得する
- URLをentrySpotのフィールドに追加する、gotDateを現在時刻で更新する

表示するとき

- URLを表示するだけ

**Comment by susatthi** [comment]
12/20にPR予定
