### ISSUE TITLE
スポット一覧をスタンプラリー詳細に統合する

### ISSUE THREAD

**Issue by susatthi** [team-musashi/stamp-rally#88]
## 関連する Issue

- #70 

## 内容

- スポット一覧画面を廃止して、スタンプラリー詳細画面内にスポット画像の一覧を表示するように変更してください
- デザイン対応は不要です

<img width="297" alt="CleanShot 2022-12-13 at 05 50 53@2x" src="https://user-images.githubusercontent.com/13707135/207151793-e5ee0332-26c4-4308-8866-c33df7c75949.png">

https://www.figma.com/file/NxKEdm3XAWdXzvbnf2oJEr/スタラリデザイン案プロトタイプ?node-id=0%3A1&t=HSOfR9o3JGQWVVwU-1

**Comment by susatthi** [comment]
Yutoさんにパス

**Comment by yuto-wl** [comment]
@susatthi 
すみません、こちらの issue は「公開中」と「参加中」の双方とも対応範囲で正しいでしょうか？

**Comment by susatthi** [comment]
@yuto-wl 

考えてなかったけど、両方お願いします！

**Comment by yuto-wl** [comment]
@susatthi 

承知しました！
参加中のページはまだこのブランチにないので、後で修正します。
