### ISSUE TITLE
【デザイン対応】公開中スタンプラリー詳細画面／スポット詳細画面

### ISSUE THREAD

**Issue by susatthi** [team-musashi/stamp-rally#92]
## 関連する Issue

- #70
- #88 の後にやる

## 内容

- 公開中スタンプラリー詳細画面のデザイン対応をお願いします。
- 以下の画面キャプチャから変更されている可能性があるので、必ず [Figma](https://www.figma.com/file/NxKEdm3XAWdXzvbnf2oJEr/スタラリデザイン案プロトタイプ?node-id=0%3A1&t=HSOfR9o3JGQWVVwU-1) を確認してください。
- スタンプラリー詳細画面の地図モードは本Issueの対象外です。
- スポット詳細画面の「SNAP SHOT」ボタンは公開中では非表示にしてください（参加中のときに使うボタンなので）。

スタンプラリー詳細画面|スポット詳細画面
--|--
![](https://user-images.githubusercontent.com/13707135/207745396-86ddcce5-2c44-44ed-8c9a-f70329985d56.png)|![](https://user-images.githubusercontent.com/13707135/207745539-a929d6a9-bbce-4f9a-9172-0f1d7b8f16f0.png)

## 目的

- UI/UX向上

**Comment by nozomi-koborinai** [comment]
@susatthi 
このIssueできそうなのでもらってもいいですか？

**Comment by susatthi** [comment]
@nozomi-koborinai 

ありがとうございます！お願いします！無理せず！

**Comment by nozomi-koborinai** [comment]
@susatthi 
スタンプラリー詳細画面の`MAPアプリを開く`ボタン押下時の仕様について、決まっていれば教えていただいてもよろしいでしょうか？

MAPアプリを開くボタン以外のところは対応完了しました！

**Comment by susatthi** [comment]
@nozomi-koborinai 

>スポット詳細画面のMAPアプリを開くボタン押下時の仕様について、決まっていれば教えていただいてもよろしいでしょうか？

GoogleMapかAppleの地図アプリが開く、でお願いします！出来なくてもOKです！

**Comment by nozomi-koborinai** [comment]
@ego-nemo 
JOIN BURARRYボタンのアイコンをsvg形式でもらうことってできますか？
<img width="742" alt="スクリーンショット 2022-12-21 10 40 09" src="https://user-images.githubusercontent.com/39579511/208800411-3b301bcc-0d64-42fb-9203-d1a2eba9c74a.png">

**Comment by ego-nemo** [comment]
SVG化して添付しました。
ご確認ください。

![JOIN _BURARRY](https://user-images.githubusercontent.com/106313781/208816461-e3c4b1a9-7c7e-4844-a1ac-0fc6a9469727.svg)
![STOP_BURARRY](https://user-images.githubusercontent.com/106313781/208816478-865a667c-e638-4c9d-9484-a0b5af282a1b.svg)

**Comment by ego-nemo** [comment]
SVG化して添付しました。
ご確認ください。

![JOIN _BURARRY](https://user-images.githubusercontent.com/106313781/208816763-68a45da7-4fe7-4853-88cc-8175e58e2501.svg)
![STOP_BURARRY](https://user-images.githubusercontent.com/106313781/208816772-d0cd0b91-cc2c-430a-9937-d3645c926fbc.svg)

**Comment by nozomi-koborinai** [comment]
@ego-nemo 
SVG化ありがとうございます！
うまくいきそうです！
