### ISSUE TITLE
【デザイン対応】【仕上げ】参加中画面／スポット詳細画面

### ISSUE THREAD

**Issue by susatthi** [team-musashi/stamp-rally#93]
## 関連する Issue

- #70
- #92 のあとにやること

## 内容

- 参加中画面とスポット詳細画面のデザイン対応をお願いします。
- 以下の画面キャプチャから変更されている可能性があるので、必ず [Figma](https://www.figma.com/file/NxKEdm3XAWdXzvbnf2oJEr/スタラリデザイン案プロトタイプ?node-id=0%3A1&t=HSOfR9o3JGQWVVwU-1) を確認してください。
- 参加中画面の地図モードは本Issueの対象外です。
- スポット詳細画面の「SNAP SHOT」ボタンは、参加中のときは表示できるようにしてください（公開中では非表示）。
- カメラもしくはギャラリーから写真をとってアップロードしてスポット到達した扱いにする処理もお願いします。

参加中画面|スポット詳細画面（撮影前）|スポット詳細画面（撮影後）
--|--|--
![](https://user-images.githubusercontent.com/13707135/207746249-c9295b0c-c743-4d65-8857-4fe50dc10172.png)|![](https://user-images.githubusercontent.com/13707135/207745539-a929d6a9-bbce-4f9a-9172-0f1d7b8f16f0.png)|![](https://user-images.githubusercontent.com/13707135/207746568-61ee6d96-371b-4efb-b2b3-859ae50e3f90.png)

## 目的

- UI/UX向上

**Comment by susatthi** [comment]
@ego-nemo 

赤枠２つの画像のSVGファイルが欲しいです！

![CleanShot 2022-12-22 at 15 56 06@2x](https://user-images.githubusercontent.com/13707135/209075549-e75c940e-2886-44c0-b217-1f6ac9c05e27.png)

**Comment by susatthi** [comment]
@ego-nemo 

SNAP SHOT
↓
SNAP SHOOT
でお願いします！

**Comment by susatthi** [comment]
@ego-nemo 

やっぱ
SNAP SHOT
のままでお願いします！

**Comment by ego-nemo** [comment]
@susatthi 
添付しました
ご確認ください

![icon_SNAPSHOT](https://user-images.githubusercontent.com/106313781/209090251-ea517938-c7f6-4366-ba1b-b8f4786bd200.svg)
![icon_DONE](https://user-images.githubusercontent.com/106313781/209090270-d79cef06-bb74-4ab8-af72-0f127efc9ef4.svg)

**Comment by ego-nemo** [comment]
![icon_SNAPSHOT](https://user-images.githubusercontent.com/106313781/209096463-ece8c5d1-a430-488e-9f24-4850c216c6e4.svg)
![icon_DONE](https://user-images.githubusercontent.com/106313781/209096548-62cd06e4-5339-4aa9-af53-22c29f6807ce.svg)

**Comment by susatthi** [comment]
大枠完了。細かいバグ修正中。明日AMにはdevelopにマージします。

**Comment by ego-nemo** [comment]
@susatthi 

参加ボタン関連アイコン
添付しました

![icon_JOIN_BURALLY](https://user-images.githubusercontent.com/106313781/209138534-0ed5c0e3-68ff-4223-a251-8ce06338661e.svg)
![icon_STOP_BURALYY](https://user-images.githubusercontent.com/106313781/209138562-0651069e-9f98-458b-95f0-5d4ff6f3d545.svg)

**Comment by ego-nemo** [comment]
修正後のロゴも置いておきます

![logo_BURALLY](https://user-images.githubusercontent.com/106313781/209142046-bf74879c-2e05-49a1-b14c-dcad55d19756.svg)
